# Generated by Django 5.2.7 on 2025-11-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(help_text="The main welcome message. e.g., 'Welcome to [NGO Name]!...'")),
                ('history_text', models.TextField(blank=True, help_text="The story behind the NGO, key milestones. e.g., 'Founded in 2015...'")),
                ('core_values_text', models.TextField(blank=True, help_text='Outline the principles (e.g., Integrity, Inclusivity...)')),
                ('areas_of_focus_text', models.TextField(blank=True, help_text='Briefly describe key focus areas. You can use markdown for bullet points.')),
                ('impact_text', models.TextField(blank=True, help_text="Share facts and statistics. e.g., 'Educated 5,000 children...'")),
                ('cta_text', models.CharField(blank=True, help_text="A strong call to action. e.g., 'Join us in making a difference...'", max_length=255)),
            ],
            options={
                'verbose_name': 'About Us Page Content',
                'verbose_name_plural': 'About Us Page Content',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g., Founder, Program Manager', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A short biography.')),
                ('image', models.ImageField(blank=True, help_text='Upload a photo of the team member.', null=True, upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display (e.g., 1, 2, 3...)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
