# Generated by Django 5.2.7 on 2025-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('projects', '0002_projectpagecontent_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='projects.project'),
        ),
    ]
