# Generated by Django 5.2.7 on 2025-11-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='A brief description of the project.')),
                ('image', models.ImageField(blank=True, help_text='Upload a photo for the project card.', null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display (e.g., 1, 2, 3...)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
