# Generated by Django 5.2.7 on 2025-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_overview', models.TextField(blank=True, help_text="Introduction for the main 'Our Projects' page.")),
                ('impact_section', models.TextField(blank=True, help_text="Text for the main 'Impact Section' (Req 4).")),
            ],
            options={
                'verbose_name': 'Projects Page Content',
                'verbose_name_plural': 'Projects Page Content',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Empowerment', 'Empowerment'), ('Environment', 'Environment'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(blank=True, help_text="Full, detailed description for the project's own page."),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_stats',
            field=models.TextField(blank=True, help_text="Key impact stats. e.g., '10,000+ children educated'. Use line breaks."),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming')], default='Ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline_info',
            field=models.TextField(blank=True, help_text="Project timeline or milestones. e.g., 'Phase 1: Completed'. Use line breaks."),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='A brief summary for the project card.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='A photo for the project card.', null=True, upload_to='projects/'),
        ),
    ]
