# Generated by Django 5.2.7 on 2025-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A caption for the photo or video.', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Upload a photo. (If this is a video, this can be a thumbnail)', null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, help_text='Optional: If this is a video, paste the full URL (e.g., from YouTube or Vimeo)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display (e.g., 1, 2, 3...)')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order'],
            },
        ),
    ]
