# Generated by Django 5.2.7 on 2025-11-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('projects', '0002_projectpagecontent_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo.', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: If this is a video, paste the full URL', null=True),
        ),
    ]
